/// Lesson data — hybrid offline/online architecture.
/// These are the LOCAL (bundled in assets) lessons available offline.
import '../models/lesson_model.dart';

// ── LOCAL LESSONS (offline, no auth needed) ────────────────
const List<Lesson> offlineLessons = [
  Lesson(
    id: 'b1',
    title: 'Ақ жүніс',
    composer: 'Халық күйі',
    difficulty: 1,
    storageType: StorageType.local,
    localImageAsset: 'assets/lessonImages/dombra_1.jpg',
    image: 'assets/lessonImages/dombra_1.jpg',
    description: 'Ақ жүністі жырлайтын жеңіл күй. Қағу техникасын дамытады.',
    audioFile: 'Ak_zhunus.mp3',
    jsonMapFile: 'akjunis_seken_turysbek.json',
    level: 'beginner',
  ),
  Lesson(
    id: 'b2',
    title: 'Кең жайлау',
    composer: 'Халық күйі',
    difficulty: 1,
    storageType: StorageType.local,
    localImageAsset: 'assets/lessonImages/dombra_2.jpg',
    image: 'assets/lessonImages/dombra_2.jpg',
    description: 'Кең жайлаудың сұлулығын суреттейтін тыныш күй.',
    audioFile: 'ken-zhailau.mp3',
    jsonMapFile: 'ken_zhaijlau_borankul_koshmagambetov.json',
    level: 'beginner',
  ),
  Lesson(
    id: 'b3',
    title: 'Сарыжайлау',
    composer: 'Тәттімбет Қазанғапұлы',
    difficulty: 2,
    storageType: StorageType.local,
    localImageAsset: 'assets/lessonImages/dombra_3.jpg',
    image: 'assets/lessonImages/dombra_3.jpg',
    description: 'Сарыжайлаудың көркемдігін жеткізетін шертпе күй.',
    audioFile: 'Sar_zhailau.mp3',
    jsonMapFile: 'saryzhalau_tattimbet_qazangapulu.json',
    level: 'beginner',
  ),
  Lesson(
    id: 'b4',
    title: 'Асыл мұра',
    composer: 'Халық күйі',
    difficulty: 2,
    storageType: StorageType.local,
    localImageAsset: 'assets/lessonImages/dombra_4.jpeg',
    image: 'assets/lessonImages/dombra_4.jpeg',
    description: 'Халық мұрасын жеткізетін әсем күй. Бастауыштарға арналған.',
    audioFile: 'Asyl_mura.mp3',
    level: 'beginner',
  ),
  Lesson(
    id: 'b5',
    title: 'Жыр күйі',
    composer: 'Халық күйі',
    difficulty: 2,
    storageType: StorageType.local,
    localImageAsset: 'assets/lessonImages/dombra_5.jpg',
    image: 'assets/lessonImages/dombra_5.jpg',
    notes: [
      GameNote(time: 1, string: 1, fret: 0, duration: 0.5),
      GameNote(time: 2, string: 1, fret: 2, duration: 0.5),
      GameNote(time: 3, string: 2, fret: 0, duration: 0.5),
      GameNote(time: 4, string: 2, fret: 3, duration: 0.5),
      GameNote(time: 5, string: 1, fret: 5, duration: 1),
      GameNote(time: 7, string: 2, fret: 5, duration: 1),
    ],
    description: 'Жүрек толқынысын жеткізетін қарапайым әуен. Бастауыштарға арналған.',
    audioFile: 'Zhyr_kui.mp3',
    level: 'beginner',
  ),
];
