/// Lesson data — hybrid offline/online architecture.
/// These are the LOCAL (bundled in assets) lessons available offline.
library;
import '../models/lesson_model.dart';

// ── LOCAL LESSONS (offline, no auth needed) ────────────────
const List<Lesson> offlineLessons = [
  Lesson(
    id: 'b1',
    title: 'Ақ жүніс',
    composer: 'Халық күйі',
    difficulty: 1,
    storageType: StorageType.local,
    localImageAsset: 'assets/lessonImages/dombra_1.webp',
    image: 'assets/lessonImages/dombra_1.webp',
    description: 'Ақ жүністі жырлайтын жеңіл күй. Қағу техникасын дамытады.',
    audioFile: 'Ak_zhunus.mp3',
    jsonMapFile: 'akjunis_seken_turysbek.json',
    level: 'beginner',
  ),
  Lesson(
    id: 'b2',
    title: 'Кең жайлау',
    composer: 'Халық күйі',
    difficulty: 1,
    storageType: StorageType.local,
    localImageAsset: 'assets/lessonImages/dombra_2.webp',
    image: 'assets/lessonImages/dombra_2.webp',
    description: 'Кең жайлаудың сұлулығын суреттейтін тыныш күй.',
    audioFile: 'ken-zhailau.mp3',
    jsonMapFile: 'ken_zhaijlau_borankul_koshmagambetov.json',
    level: 'beginner',
  ),
  Lesson(
    id: 'b3',
    title: 'Сарыжайлау',
    composer: 'Тәттімбет Қазанғапұлы',
    difficulty: 2,
    storageType: StorageType.local,
    localImageAsset: 'assets/lessonImages/dombra_3.webp',
    image: 'assets/lessonImages/dombra_3.webp',
    description: 'Сарыжайлаудың көркемдігін жеткізетін шертпе күй.',
    audioFile: 'Sar_zhailau.mp3',
    jsonMapFile: 'saryzhalau_tattimbet_qazangapulu.json',
    level: 'beginner',
  ),
  Lesson(
    id: 'b4',
    title: 'Келіншек күйі',
    composer: 'Халық күйі',
    difficulty: 1,
    storageType: StorageType.local,
    localImageAsset: 'assets/lessonImages/dombra_4.webp',
    image: 'assets/lessonImages/dombra_4.webp',
    description: 'Жеңіл әрі ойнақы күй. Бастауыштарға өте қолайлы.',
    audioFile: 'Kelinshek_kuyi.mp3',
    jsonMapFile: 'kelinshek_kuyi.json',
    level: 'beginner',
  ),
  Lesson(
    id: 'b5',
    title: 'Көзімнің қарасы',
    composer: 'Абай Құнанбайұлы',
    difficulty: 1,
    storageType: StorageType.local,
    localImageAsset: 'assets/lessonImages/dombra_5.webp',
    image: 'assets/lessonImages/dombra_5.webp',
    description: 'Абайдың әйгілі әнінің оңайлатылған нұсқасы.',
    audioFile: 'kozimnin_karasy_abay_kunanbayulu.mp3',
    jsonMapFile: 'kozimnin_karasy_easy.json',
    level: 'beginner',
  ),
];
