import '../models/lesson.dart';

const List<Lesson> kBeginnerLessons = [
  Lesson(id: 'b1', title: 'Көңіл толқыны', composer: 'Халық күйі', difficulty: 1, progress: 0, isPremium: false, level: 'beginner', image: 'assets/images/lessons/dombra_1.jpg', notes: [], description: 'Жүрек толқынысын жеткізетін қарапайым әуен.', audioFile: 'Konil tolkyny.mp3'),
  Lesson(id: 'b2', title: 'Жем суының тасқыны', composer: 'Халық күйі', difficulty: 2, progress: 0, isPremium: false, level: 'beginner', image: 'assets/images/lessons/dombra_2.jpg', notes: [], description: 'Жем өзенінің тасқынын суреттейтін күй.', audioFile: 'Zhem_suynyn_taskyny.mp3'),
  Lesson(id: 'b3', title: 'Ақ жүніс', composer: 'Халық күйі', difficulty: 2, progress: 0, isPremium: false, level: 'beginner', image: 'assets/images/lessons/dombra_3.jpg', notes: [], description: 'Ақ жүністі жырлайтын жеңіл күй.', audioFile: 'ak-junis-kui.mp3'),
  Lesson(id: 'b4', title: 'Ақсақ құлан', composer: 'Халық күйі', difficulty: 1, progress: 0, isPremium: false, level: 'beginner', image: 'assets/images/lessons/dombra_4.jpg', notes: [], description: 'Аңызға толы ежелгі күй.', audioFile: 'aksak-kulan.mp3'),
  Lesson(id: 'b5', title: 'Аққу', composer: 'Халық күйі', difficulty: 2, progress: 0, isPremium: false, level: 'beginner', image: 'assets/images/lessons/dombra_5.webp', notes: [], description: 'Аққу құстың сұлулығын бейнелейтін мелодиялық күй.', audioFile: 'aqqu.mp3'),
  Lesson(id: 'b6', title: 'Хафиз', composer: 'Халық күйі', difficulty: 2, progress: 0, isPremium: false, level: 'beginner', image: 'assets/images/lessons/dombra_6.jpg', notes: [], description: 'Хафиз ақынға арналған ырғақты күй.', audioFile: 'hafiz.mp3'),
  Lesson(id: 'b7', title: 'Кең жайлау', composer: 'Халық күйі', difficulty: 1, progress: 0, isPremium: false, level: 'beginner', image: 'assets/images/lessons/dombra_7.png', notes: [], description: 'Кең жайлаудың сұлулығын суреттейтін тыныш күй.', audioFile: 'ken-zhaijlau.mp3'),
  Lesson(id: 'b8', title: 'Көш керуен', composer: 'Халық күйі', difficulty: 2, progress: 0, isPremium: false, level: 'beginner', image: 'assets/images/lessons/dombra_8.jpg', notes: [], description: 'Көшпелі кервеннің жолын бейнелейтін күй.', audioFile: 'kosh-keruen.mp3'),
  Lesson(id: 'b9', title: 'Құрманғазы', composer: 'Құрманғазы Сағырбайұлы', difficulty: 2, progress: 0, isPremium: false, level: 'beginner', image: 'assets/images/lessons/dombra_9.jpeg', notes: [], description: 'Ұлы күйшіге арналған қарапайым нұсқа.', audioFile: 'kurmangazi.mp3'),
  Lesson(id: 'b10', title: 'Сарыжайлау', composer: 'Тәттімбет Қазанғапұлы', difficulty: 2, progress: 0, isPremium: false, level: 'beginner', image: 'assets/images/lessons/dombra_10.jpg', notes: [], description: 'Сарыжайлаудың көркемдігін жеткізетін шертпе күй.', audioFile: 'saryzhalau.mp3'),
  Lesson(id: 'b11', title: 'Шақыру', composer: 'Халық күйі', difficulty: 1, progress: 0, isPremium: false, level: 'beginner', image: 'assets/images/lessons/dombra_11.jpg', notes: [], description: 'Шақыру мәнді жеткізетін жеңіл күй.', audioFile: 'shakyruy-kui.mp3'),
  Lesson(id: 'b12', title: 'Қосалқа', composer: 'Дәулеткерей Шығайұлы', difficulty: 2, progress: 0, isPremium: false, level: 'beginner', image: 'assets/images/lessons/dombra_12.jpg', notes: [], description: 'Дәулеткерейдің әйгілі күйінің қарапайым нұсқасы.', audioFile: 'Дәулеткерей — Қосалқа.mp3'),
];

const List<Lesson> kProLessons = [
  Lesson(id: 'p1', title: 'Әсем қоңыр', composer: 'Халық күйі', difficulty: 4, progress: 0, isPremium: true, level: 'pro', image: 'assets/images/lessons/dombra_13.jpg', notes: [], description: 'Күрделі орнаментті күй.', audioFile: '10.Кюй - Асем коныр.mp3'),
  Lesson(id: 'p2', title: 'Балқылдақ', composer: 'Халық күйі', difficulty: 4, progress: 0, isPremium: true, level: 'pro', image: 'assets/images/lessons/dombra_14.jpg', notes: [], description: 'Жарқыраған, виртуозды күй.', audioFile: '11.Кюй - Балкылдак.mp3'),
  Lesson(id: 'p3', title: 'Ақсақ құлан II', composer: 'Халық күйі', difficulty: 4, progress: 0, isPremium: true, level: 'pro', image: 'assets/images/lessons/dombra_15.jpg', notes: [], description: 'Ақсақ құланның күрделі нұсқасы.', audioFile: '13.Кюй - Аксак кулан II.mp3'),
  Lesson(id: 'p4', title: 'Жеңгем сүйір', composer: 'Халық күйі', difficulty: 3, progress: 0, isPremium: true, level: 'pro', image: 'assets/images/lessons/dombra_16.jpg', notes: [], description: 'Жеңгелер жырын орындайтын ырғақты күй.', audioFile: '14.Кюй - Женгем суйыр.mp3'),
  Lesson(id: 'p5', title: 'Сайжарлау', composer: 'Халық күйі', difficulty: 4, progress: 0, isPremium: true, level: 'pro', image: 'assets/images/lessons/dombra_17.jpg', notes: [], description: 'Жайлау көркемдігін виртуозды орындаумен жеткізетін күй.', audioFile: '20.Кюй - Сайжарляу.mp3'),
  Lesson(id: 'p6', title: 'Салқыма', composer: 'Халық күйі', difficulty: 4, progress: 0, isPremium: true, level: 'pro', image: 'assets/images/lessons/dombra_18.jpg', notes: [], description: 'Халық дәстүріндегі күрделі күй.', audioFile: '24.Кюй - Салкыма.mp3'),
  Lesson(id: 'p7', title: 'Соқыр Есжан', composer: 'Халық күйі', difficulty: 3, progress: 0, isPremium: true, level: 'pro', image: 'assets/images/lessons/dombra_1.jpg', notes: [], description: 'Есжан ақынға арналған терең мазмұнды күй.', audioFile: '25.Кюй - Сокыр Есжан.mp3'),
  Lesson(id: 'p8', title: 'Салқылдақ', composer: 'Халық күйі', difficulty: 4, progress: 0, isPremium: true, level: 'pro', image: 'assets/images/lessons/dombra_2.jpg', notes: [], description: 'Жылдам ырғақтағы виртуозды күй.', audioFile: '26.Кюй - Салкылдак.mp3'),
  Lesson(id: 'p9', title: 'Ақсақ құлан', composer: 'Халық күйі', difficulty: 4, progress: 0, isPremium: true, level: 'pro', image: 'assets/images/lessons/dombra_3.jpg', notes: [], description: 'Ақсақ құланның виртуозды нұсқасы.', audioFile: '7.Кюй - Аксак кулан.mp3'),
  Lesson(id: 'p10', title: 'Алатау', composer: 'Халық күйі', difficulty: 5, progress: 0, isPremium: true, level: 'pro', image: 'assets/images/lessons/dombra_4.jpg', notes: [], description: 'Алатау тауларының салтанатын бейнелейтін концерттік күй.', audioFile: '8.Кюй - Алатау.mp3'),
  Lesson(id: 'p11', title: 'Аншының зары', composer: 'Халық күйі', difficulty: 4, progress: 0, isPremium: true, level: 'pro', image: 'assets/images/lessons/dombra_5.webp', notes: [], description: 'Аншының зар мұңын жеткізетін эмоционалды күй.', audioFile: '9.Кюй - Аншынын зары.mp3'),
  Lesson(id: 'p12', title: 'Адай', composer: 'Құрманғазы Сағырбайұлы', difficulty: 5, progress: 0, isPremium: true, level: 'pro', image: 'assets/images/lessons/dombra_6.jpg', notes: [], description: 'Құрманғазының ұлы туындысы.', audioFile: 'adai.mp3'),
  Lesson(id: 'p13', title: 'Бекеттің зар-күйі', composer: 'Бекет', difficulty: 5, progress: 0, isPremium: true, level: 'pro', image: 'assets/images/lessons/dombra_7.png', notes: [], description: 'Зар мұңды жеткізетін күрделі шығарма.', audioFile: 'bekettin-zar-kuii.mp3'),
  Lesson(id: 'p14', title: 'Еркі сылқым', composer: 'Халық күйі', difficulty: 4, progress: 0, isPremium: true, level: 'pro', image: 'assets/images/lessons/dombra_8.jpg', notes: [], description: 'Нәзік, сылқым мезөнді жеткізетін виртуозды күй.', audioFile: 'erke-sylkym.mp3'),
  Lesson(id: 'p15', title: 'Малғаждар', composer: 'Халық күйі', difficulty: 5, progress: 0, isPremium: true, level: 'pro', image: 'assets/images/lessons/dombra_9.jpeg', notes: [], description: 'Батырлық рухтағы эпикалық күй.', audioFile: 'malgajdar-kui.mp3'),
  Lesson(id: 'p16', title: 'Ноғай хандығы', composer: 'Халық күйі', difficulty: 5, progress: 0, isPremium: true, level: 'pro', image: 'assets/images/lessons/dombra_10.jpg', notes: [], description: 'Тарихи күй. Ноғай хандығының дәуірін бейнелейді.', audioFile: 'nogai-handygi.mp3'),
  Lesson(id: 'p17', title: 'Кеңес', composer: 'Халық күйі', difficulty: 4, progress: 0, isPremium: true, level: 'pro', image: 'assets/images/lessons/dombra_11.jpg', notes: [], description: 'Кеңес беретін мәнді күй.', audioFile: 'Халық күйі - Кеңес.mp3'),
];

const List<Lesson> kAllLessons = [...kBeginnerLessons, ...kProLessons];
